language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: clang

    - os: linux
      dist: bionic
      compiler: gcc

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libgtk-3-dev libnotify-dev libbz2-dev libssl-dev

install:
  make
